export const ErrorCodes = {
  AUTH: {
    TOKEN_MISSING: 'auth.token_missing',
    JWT_EXPIRED: 'auth.jwt_expired',
    INVALID_SIGNATURE: 'auth.invalid_signature',
    INVALID_TOKEN: 'auth.invalid_token',
    UNAUTHORIZED: 'auth.unauthorized',
    ACCOUNT_BLOCKED: 'auth.account_blocked',
    ACCOUNT_DELETED: 'auth.account_deleted',
    ACCOUNT_INACTIVE: 'auth.account_inactive',
    USER_NOT_FOUND: 'auth.user_not_found',
    USER_NOT_AUTHENTICATED: 'auth.user_not_authenticated',
    INVALID_CREDENTIALS: 'auth.invalid_credentials',
  },
  USER: {
    NOT_FOUND: 'user.not_found',
    BLOCKED: 'user.blocked',
    DELETED: 'user.deleted',
    INACTIVE: 'user.inactive',
    EMAIL_EXISTS: 'user.email_exists',
    USERNAME_EXISTS: 'user.username_exists',
    INVALID_ROLE: 'user.invalid_role',
    CREATION_FAILED: 'user.creation_failed',
    UPDATE_FAILED: 'user.update_failed',
    DELETE_FAILED: 'user.delete_failed',
    CANNOT_DELETE_SELF: 'user.cannot_delete_self',
    CANNOT_UPDATE_SELF_ROLE: 'user.cannot_update_self_role',
    PASSWORD_CHANGE_FAILED: 'user.password_change_failed',
    PASSWORD_INCORRECT: 'user.password_incorrect',
  },
  STUDENT: {
    NOT_FOUND: 'student.not_found',
    STUDENT_ID_EXISTS: 'student.student_id_exists',
    EMAIL_EXISTS: 'student.email_exists',
    USERNAME_EXISTS: 'student.username_exists',
    CREATION_FAILED: 'student.creation_failed',
    UPDATE_FAILED: 'student.update_failed',
    DELETE_FAILED: 'student.delete_failed',
    FETCH_FAILED: 'student.fetch_failed',
    UNKNOWN_ERROR: 'student.unknown_error',
    ARCHIVED: 'student.archived',
    PENDING_APPLICATION: 'student.pending_application',
    REJECTED_APPLICATION: 'student.rejected_application',
  },
  ANNOUNCEMENT: {
    NOT_FOUND: 'announcement.not_found',
    CREATION_FAILED: 'announcement.creation_failed',
    UPDATE_FAILED: 'announcement.update_failed',
    DELETE_FAILED: 'announcement.delete_failed',
    FETCH_FAILED: 'announcement.fetch_failed',
    UNKNOWN_ERROR: 'announcement.unknown_error',
    INVALID_DATES: 'announcement.invalid_dates',
  },
  TIMELOG: {
    NOT_FOUND: 'timelog.not_found',
    CREATION_FAILED: 'timelog.creation_failed',
    UPDATE_FAILED: 'timelog.update_failed',
    DELETE_FAILED: 'timelog.delete_failed',
    FETCH_FAILED: 'timelog.fetch_failed',
    UNKNOWN_ERROR: 'timelog.unknown_error',
    ALREADY_CLOCKED_IN: 'timelog.already_clocked_in',
    NOT_CLOCKED_IN: 'timelog.not_clocked_in',
    INVALID_ACTION: 'timelog.invalid_action',
    STUDENT_REQUIRED: 'timelog.student_required',
  },
  SUBMISSION: {
    NOT_FOUND: 'submission.not_found',
    CREATION_FAILED: 'submission.creation_failed',
    UPDATE_FAILED: 'submission.update_failed',
    DELETE_FAILED: 'submission.delete_failed',
    FETCH_FAILED: 'submission.fetch_failed',
    UNKNOWN_ERROR: 'submission.unknown_error',
    FILE_REQUIRED: 'submission.file_required',
    FILE_TOO_LARGE: 'submission.file_too_large',
    INVALID_FILE_TYPE: 'submission.invalid_file_type',
    ALREADY_SUBMITTED: 'submission.already_submitted',
    PAST_DUE_DATE: 'submission.past_due_date',
  },
  REQUIREMENT: {
    NOT_FOUND: 'requirement.not_found',
    CREATION_FAILED: 'requirement.creation_failed',
    UPDATE_FAILED: 'requirement.update_failed',
    DELETE_FAILED: 'requirement.delete_failed',
    FETCH_FAILED: 'requirement.fetch_failed',
    UNKNOWN_ERROR: 'requirement.unknown_error',
  },
  GRADE: {
    NOT_FOUND: 'grade.not_found',
    CREATION_FAILED: 'grade.creation_failed',
    UPDATE_FAILED: 'grade.update_failed',
    DELETE_FAILED: 'grade.delete_failed',
    FETCH_FAILED: 'grade.fetch_failed',
    UNKNOWN_ERROR: 'grade.unknown_error',
    INVALID_SCORE: 'grade.invalid_score',
    STUDENT_REQUIRED: 'grade.student_required',
  },
  NOTIFICATION: {
    NOT_FOUND: 'notification.not_found',
    CREATION_FAILED: 'notification.creation_failed',
    UPDATE_FAILED: 'notification.update_failed',
    DELETE_FAILED: 'notification.delete_failed',
    FETCH_FAILED: 'notification.fetch_failed',
    MARK_READ_FAILED: 'notification.mark_read_failed',
    UNKNOWN_ERROR: 'notification.unknown_error',
  },
  SCHEDULE: {
    NOT_FOUND: 'schedule.not_found',
    CREATION_FAILED: 'schedule.creation_failed',
    UPDATE_FAILED: 'schedule.update_failed',
    DELETE_FAILED: 'schedule.delete_failed',
    FETCH_FAILED: 'schedule.fetch_failed',
    CONFLICT: 'schedule.conflict',
    INVALID_TIME: 'schedule.invalid_time',
    UNKNOWN_ERROR: 'schedule.unknown_error',
  },
  CONTENT: {
    NOT_FOUND: 'content.not_found',
    CREATION_FAILED: 'content.creation_failed',
    UPDATE_FAILED: 'content.update_failed',
    DELETE_FAILED: 'content.delete_failed',
    FETCH_FAILED: 'content.fetch_failed',
    UNKNOWN_ERROR: 'content.unknown_error',
  },
  GENERAL: {
    UNKNOWN_ERROR: 'general.unknown_error',
    VALIDATION_ERROR: 'general.validation_error',
    BAD_REQUEST: 'general.bad_request',
    DATABASE_ERROR: 'general.database_error',
    FILE_UPLOAD_FAILED: 'general.file_upload_failed',
    MISSING_REQUIRED_FIELDS: 'general.missing_required_fields',
    EMAIL_ALREADY_EXISTS: 'general.email_already_exists',
    USERNAME_ALREADY_EXISTS: 'general.username_already_exists',
    STUDENT_ID_ALREADY_EXISTS: 'general.student_id_already_exists',
    INVALID_ACTION: 'general.invalid_action',
    PRECONDITIONS_NOT_MET: 'general.preconditions_not_met',
    INTERNAL_SERVER_ERROR: 'general.internal_server_error',
  },
} as const;

export const ERROR_CODES = ErrorCodes;
