export const SuccessCodes = {
  AUTH: {
    LOGIN: 'auth.login',
    LOGOUT: 'auth.logout',
    REGISTER: 'auth.register',
    REGISTRATION_PENDING: 'auth.registration_pending',
    TOKEN_REFRESH: 'auth.token_refreshed',
    PASSWORD_CHANGED: 'auth.password_changed',
    PASSWORD_RESET: 'auth.password_reset',
  },
  USER: {
    CREATED: 'user.created',
    UPDATED: 'user.updated',
    DELETED: 'user.deleted',
    RETRIEVED: 'user.retrieved',
    FETCHED: 'user.fetched',
  },
  STUDENT: {
    CREATED: 'student.created',
    UPDATED: 'student.updated',
    DELETED: 'student.deleted',
    FETCHED: 'student.fetched',
    RETRIEVED: 'student.retrieved',
    APPROVED: 'student.approved',
    REJECTED: 'student.rejected',
    ARCHIVED: 'student.archived',
    UNARCHIVED: 'student.unarchived',
  },
  ANNOUNCEMENT: {
    CREATED: 'announcement.created',
    UPDATED: 'announcement.updated',
    DELETED: 'announcement.deleted',
    FETCHED: 'announcement.fetched',
    RETRIEVED: 'announcement.retrieved',
  },
  TIMELOG: {
    CREATED: 'timelog.created',
    UPDATED: 'timelog.updated',
    DELETED: 'timelog.deleted',
    FETCHED: 'timelog.fetched',
    CLOCKED_IN: 'timelog.clocked_in',
    CLOCKED_OUT: 'timelog.clocked_out',
    LUNCH_IN: 'timelog.lunch_in',
    LUNCH_OUT: 'timelog.lunch_out',
  },
  SUBMISSION: {
    CREATED: 'submission.created',
    UPDATED: 'submission.updated',
    DELETED: 'submission.deleted',
    FETCHED: 'submission.fetched',
    RETRIEVED: 'submission.retrieved',
    APPROVED: 'submission.approved',
    REJECTED: 'submission.rejected',
    RETURNED_FOR_REVISION: 'submission.returned_for_revision',
  },
  REQUIREMENT: {
    CREATED: 'requirement.created',
    UPDATED: 'requirement.updated',
    DELETED: 'requirement.deleted',
    FETCHED: 'requirement.fetched',
    RETRIEVED: 'requirement.retrieved',
  },
  GRADE: {
    CREATED: 'grade.created',
    UPDATED: 'grade.updated',
    DELETED: 'grade.deleted',
    FETCHED: 'grade.fetched',
    RETRIEVED: 'grade.retrieved',
    CALCULATED: 'grade.calculated',
  },
  NOTIFICATION: {
    CREATED: 'notification.created',
    UPDATED: 'notification.updated',
    DELETED: 'notification.deleted',
    FETCHED: 'notification.fetched',
    MARKED_AS_READ: 'notification.marked_as_read',
    MARKED_ALL_AS_READ: 'notification.marked_all_as_read',
  },
  SCHEDULE: {
    CREATED: 'schedule.created',
    UPDATED: 'schedule.updated',
    DELETED: 'schedule.deleted',
    FETCHED: 'schedule.fetched',
    RETRIEVED: 'schedule.retrieved',
  },
  CONTENT: {
    CREATED: 'content.created',
    UPDATED: 'content.updated',
    DELETED: 'content.deleted',
    FETCHED: 'content.fetched',
    RETRIEVED: 'content.retrieved',
  },
  GENERAL: {
    OK: 'general.ok',
    CREATED: 'general.created',
    UPDATED: 'general.updated',
    DELETED: 'general.deleted',
    SUCCESS: 'general.success',
  },
} as const;

export const SUCCESS_CODES = SuccessCodes;
